/*1. Muestra, maquetada en una tabla HTML toda la informaci n que puedas ó
extraer mediante JavaScript del navegador cliente.*/
document.write("<strong>Información con navigator</strong>");
document.write("<br>");
document.write("<table border=1>");
  document.write("<tr>");
    document.write("<td>Nombre del codigo del navegador:</td>");
    document.write("<td>"+navigator.appCodeName+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Nombre del navegador:</td>");
    document.write("<td>"+navigator.appName+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Informacion del navegador:</td>");
    document.write("<td>"+navigator.appVersion+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Cookies activas:</td>");
    document.write("<td>"+navigator.cookieEnabled+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Geolocalización:</td>");
    document.write("<td>"+navigator.geolocation+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Idioma:</td>");
    document.write("<td>"+navigator.language+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>En Linea:</td>");
    document.write("<td>"+navigator.onLine+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Plataforma del navegador:</td>");
    document.write("<td>"+navigator.platform+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>El motor del navegador:</td>");
    document.write("<td>"+navigator.product+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Nombre del agente del navegador:</td>");
    document.write("<td>"+navigator.userAgent+"</td>");
  document.write("</tr>");
document.write("</table>");

/*2. Realiza lo mismo para la información de la pantalla utilizada por el cliente. */
document.write("<br><br><br>");
document.write("<strong>Informacion de la pantalla</strong>");
document.write("<br>");
document.write("<table border=1>");
  document.write("<tr>");
    document.write("<td>Resolución de pantalla:</td>");
    document.write("<td>"+screen.width + "" + screen.height+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Area visible disponible:</td>");
    document.write("<td>"+screen.availWidth+""+screen.availHeight+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Profundidad de color:</td>");
    document.write("<td>"+screen.colorDepth+"</td>");
  document.write("</tr>");
  document.write("<tr>");
    document.write("<td>Resolución de color:</td>");
    document.write("<td>"+screen.pixelDepth+"</td>");
  document.write("</tr>");
document.write("</table>");
